repos:
  - repo: local
    hooks:
      - id: ai-review
        name: AI Code Review
        entry: ./scripts/ai-review-go.sh
        language: script
        files: \.go$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # or latest
    hooks:
      - id: trailing-whitespace

